import json
from typing import Any, Dict

def kaizen_proposal_to_pr_draft(proposal_ndjson: str) -> str:
    """
    Parses a KaizenProposal NDJSON string and returns a formatted Markdown string
    suitable for a GitHub Pull Request body.
    """
    try:
        proposal: Dict[str, Any] = json.loads(proposal_ndjson)
    except json.JSONDecodeError as e:
        raise ValueError("Invalid NDJSON string") from e

    kind = proposal.get("kind")
    if kind != "kaizen-proposal":
        raise ValueError(f"Expected kind 'kaizen-proposal', got '{kind}'")

    rule_id = proposal.get("ruleId", "unknown")
    category = proposal.get("category", "unknown")
    severity = proposal.get("severity", "info")
    summary = proposal.get("summary", "No summary provided")
    detail = proposal.get("detail", "No details provided")

    suggested_action = proposal.get("suggestedAction", {})
    action_desc = suggested_action.get("description", "No description provided")
    patch_hint = suggested_action.get("patchHint", "")
    target_files = suggested_action.get("targetFiles", [])
    test_plan = suggested_action.get("testPlan", [])

    pr_agent_hint = proposal.get("prAgentHint", {})
    labels = pr_agent_hint.get("labels", [])

    # Formatting the markdown
    md = f"## Kaizen Proposal: {summary}\n\n"
    md += f"**Rule ID:** `{rule_id}`\n"
    md += f"**Category:** {category}\n"
    md += f"**Severity:** {severity.upper()}\n\n"

    md += "### Detail\n"
    md += f"{detail}\n\n"

    md += "### Suggested Action\n"
    md += f"{action_desc}\n\n"

    if target_files:
        md += "**Target Files:**\n"
        for f in target_files:
            md += f"- `{f}`\n"
        md += "\n"

    if patch_hint:
        md += f"**Patch Hint:**\n```\n{patch_hint}\n```\n\n"

    if test_plan:
        md += "### Test Plan\n"
        for i, step in enumerate(test_plan, 1):
            md += f"{i}. {step}\n"
        md += "\n"

    if labels:
        md += f"**Labels:** {', '.join(labels)}\n\n"

    md += "---\n*This PR was generated by the ecosystem Kaizen PR agent.*"

    return md
