(ns kotoba.test-runner
  "Aggregate test entry point for `clojure -M:test`."
  (:require [clojure.test :refer [run-tests]]
            [kotoba.actor-host-test]
            [kotoba.anchor-relayer-test]
            [kotoba.bounded-cbor-test]
            [kotoba.cold-tier-admission-test]
            [kotoba.compositional-negative-test]
            [kotoba.control-adoption-test]
            [kotoba.crypto-qualification-test]
            [kotoba.grade-a-test]
            [kotoba.kbb-data-json-test]
            [kotoba.kbb-data-edn-test]
            [kotoba.kbb-facade-scan-test]
            [kotoba.kbb-env-read-test]
            [kotoba.kbb-gate-scripts-test]
            [kotoba.kbb-scripts-port-test]
            [kotoba.kbb-http-fetch-test]
            [kotoba.string-search-test]
            [kotoba.kbb-proc-exec-test]
            [kotoba.kbb-native-test]
            [kotoba.kbb-shim-test]
            [kotoba.kbb-js-test]
            [kotoba.kbb-js-providers-test]
            [kotoba.kbb-js-write-test]
            [kotoba.kbb-js-cli-test]
            [kotoba.kbb-lib-test]
            [kotoba.key-hierarchy-test]
            [kotoba.origin-assertion-test]
            [kotoba.sealed-egress-test]
            [kotoba.semantic-codebase-test]
            [kotoba.test-runner-completeness-test]
            [kotoba.kagi-boundary-test]
            [kotoba.hybrid-envelope-test]
            [kotoba.package-admission-test]
            [kotoba.package-install-test]
            [kotoba.release-build-test]
            [kotoba.wasm-multi-source-map-test]
            [kotoba.wasm-string-literal-operation-test]
            [kotoba.typed-collection-wasm-test]
            [kotoba.backend-qualification-test]
            [kotoba.aiueos-kernel-caps-test]
            [kotoba.cacao-run-test]
            [kotoba.cap-affine-test]
            [kotoba.cap-passing-test]
            [kotoba.cap-table-test]
            [kotoba.cap-use-kotoba-parity-test]
            [kotoba.capability-cross-layer-test]
            [kotoba.cap-typed-test]
            [kotoba.cljs-backend-test]
            [kotoba.did-adapter-test]
            [kotoba.doc-examples-test]
            [kotoba.guest-grammar-vendor-test]
            [kotoba.guest-maturity-l2-test]
            [kotoba.guest-maturity-p0-p1-test]
            [kotoba.guest-maturity-l3-l5-test]
            [kotoba.guest-maturity-l4-l6-test]
            [kotoba.git-adapter-test]
            [kotoba.graph-adapter-test]
            [kotoba.deploy-adapter-test]
            [kotoba.host-providers-test]
            [kotoba.host-write-window-test]
            [kotoba.kami-game-test]
            [kotoba.kgraph-test]
            [kotoba.codebase-cli-test]
            [kotoba.codebase-compile-test]
            [kotoba.codebase-ipns-test]
            [kotoba.codebase-publish-test]
            [kotoba.codebase-typed-test]
            [kotoba.launcher-test]
            [kotoba.operator-identity-test]
            [kotoba.principal-identity-test]
            [kotoba.language-conformance-test]
            [kotoba.library-release-test]
            [kotoba.codebase-routing-provider-test]
            [kotoba.package-registry-test]
            [kotoba.package-key-revoke-e2e-test]
            [kotoba.rad-adapter-test]
            [kotoba.raw-memory-test]
            [kotoba.real-host-providers-test]
            [kotoba.reproducible-emit-test]
            [kotoba.resource-scope-kotoba-parity-test]
            [kotoba.runtime-test]
            [kotoba.security-by-design-assurance-test]
            [kotoba.security-kaizen-test]
            [kotoba.security-boundary-fuzz-test]
            [kotoba.sensing-host-test]
            [kotoba.semantic-code-integration-test]
            [kotoba.type-contract-adapter-test]
            [kotoba.transport-component-test]
            [kotoba.wasm-and-or-when-test]
            [kotoba.wasm-assert-test]
            [kotoba.wasm-case-test]
            [kotoba.wasm-condp-test]
            [kotoba.wasm-doseq-test]
            [kotoba.wasm-binding-conditionals-test]
            [kotoba.wasm-dotimes-test]
            [kotoba.wasm-some-sugar-test]
            [kotoba.wasm-exec-test]
            [kotoba.wasm-map-keyword-test]
            [kotoba.wasm-multimethod-test]
            [kotoba.wasm-record-protocol-test]
            [kotoba.wasm-threading-test]))

(defn -main [& _]
  (let [{:keys [fail error]} (run-tests 'kotoba.actor-host-test
                                        'kotoba.anchor-relayer-test
                                        'kotoba.bounded-cbor-test
                                        'kotoba.cold-tier-admission-test
                                        'kotoba.compositional-negative-test
                                        'kotoba.control-adoption-test
                                        'kotoba.crypto-qualification-test
                                        'kotoba.grade-a-test
                                        'kotoba.kbb-data-json-test
                                        'kotoba.kbb-data-edn-test
                                        'kotoba.kbb-facade-scan-test
                                        'kotoba.kbb-env-read-test
                                        'kotoba.kbb-gate-scripts-test
                                        'kotoba.kbb-scripts-port-test
                                        'kotoba.kbb-http-fetch-test
                                        'kotoba.string-search-test
                                        'kotoba.kbb-proc-exec-test
                                        'kotoba.kbb-native-test
                                        'kotoba.kbb-shim-test
                                        'kotoba.kbb-js-test
                                        'kotoba.kbb-js-providers-test
                                        'kotoba.kbb-js-write-test
                                        'kotoba.kbb-js-cli-test
                                        'kotoba.kbb-lib-test
                                        'kotoba.key-hierarchy-test
                                        'kotoba.origin-assertion-test
                                        'kotoba.sealed-egress-test
                                        'kotoba.semantic-codebase-test
                                        'kotoba.test-runner-completeness-test
                                        'kotoba.kagi-boundary-test
                                        'kotoba.hybrid-envelope-test
                                        'kotoba.package-admission-test
                                        'kotoba.package-install-test
                                        'kotoba.release-build-test
                                        'kotoba.wasm-multi-source-map-test
                                        'kotoba.wasm-string-literal-operation-test
                                        'kotoba.typed-collection-wasm-test
                                        'kotoba.backend-qualification-test
                                        'kotoba.aiueos-kernel-caps-test
                                        'kotoba.cacao-run-test
                                        'kotoba.cap-affine-test
                                        'kotoba.cap-passing-test
                                        'kotoba.cap-table-test
                                        'kotoba.cap-use-kotoba-parity-test
                                        'kotoba.capability-cross-layer-test
                                        'kotoba.cap-typed-test
                                        'kotoba.cljs-backend-test
                                        'kotoba.did-adapter-test
                                        'kotoba.doc-examples-test
                                        'kotoba.guest-grammar-vendor-test
                                        'kotoba.guest-maturity-l2-test
                                        'kotoba.guest-maturity-p0-p1-test
                                        'kotoba.guest-maturity-l3-l5-test
                                        'kotoba.guest-maturity-l4-l6-test
                                        'kotoba.git-adapter-test
                                        'kotoba.graph-adapter-test
                                        'kotoba.deploy-adapter-test
                                        'kotoba.host-providers-test
                                        'kotoba.host-write-window-test
                                        'kotoba.kami-game-test
                                        'kotoba.kgraph-test
                                        'kotoba.codebase-cli-test
                                        'kotoba.codebase-compile-test
                                        'kotoba.codebase-ipns-test
                                        'kotoba.codebase-publish-test
                                        'kotoba.codebase-typed-test
                                        'kotoba.launcher-test
                                        'kotoba.operator-identity-test
                                        'kotoba.principal-identity-test
                                        'kotoba.language-conformance-test
             'kotoba.library-release-test
             'kotoba.codebase-routing-provider-test
                                        'kotoba.package-registry-test
                                        'kotoba.package-key-revoke-e2e-test
                                        'kotoba.rad-adapter-test
                                        'kotoba.raw-memory-test
                                        'kotoba.real-host-providers-test
                                        'kotoba.reproducible-emit-test
                                        'kotoba.resource-scope-kotoba-parity-test
                                        'kotoba.runtime-test
                                        'kotoba.security-by-design-assurance-test
                                        'kotoba.security-kaizen-test
                                        'kotoba.security-boundary-fuzz-test
                                        'kotoba.sensing-host-test
                                        'kotoba.semantic-code-integration-test
                                        'kotoba.type-contract-adapter-test
                                        'kotoba.transport-component-test
                                        'kotoba.wasm-and-or-when-test
                                        'kotoba.wasm-assert-test
                                        'kotoba.wasm-case-test
                                        'kotoba.wasm-condp-test
                                        'kotoba.wasm-doseq-test
                                        'kotoba.wasm-binding-conditionals-test
                                        'kotoba.wasm-dotimes-test
                                        'kotoba.wasm-some-sugar-test
                                        'kotoba.wasm-exec-test
                                        'kotoba.wasm-map-keyword-test
                                        'kotoba.wasm-multimethod-test
                                        'kotoba.wasm-record-protocol-test
                                        'kotoba.wasm-threading-test)]
    (System/exit (if (pos? (+ (or fail 0) (or error 0))) 1 0))))
