import json
import pytest
from kotodama.organism.kaizen.proposal_to_pr_draft import kaizen_proposal_to_pr_draft

def test_kaizen_proposal_valid_full():
    proposal = {
        "v": 1,
        "ts": 1748131234567,
        "kind": "kaizen-proposal",
        "ruleId": "sweep-latency-p95",
        "category": "performance",
        "severity": "warn",
        "actorScope": "shard:1",
        "summary": "shard-1 sweep p95 = 8.2s (target <= 1s)",
        "detail": "Over the last 24 ticks issachar's tick durationMs has averaged 8,150 ms.",
        "suggestedAction": {
            "kind": "config-change",
            "description": "Increase LRU_MAX from 4096 to 16384 on shard-1.",
            "targetFiles": ["50-infra/k8s/unispsc-organism-fleet/shard-1/daemonset.yaml"],
            "patchHint": 'env UNISPSC_ORGANISM_LRU_MAX: "4096" -> "16384"',
            "testPlan": [
                "Re-apply manifest, wait 30 min",
                "Verify tickDurationMsP95 < 1000"
            ]
        },
        "prAgentHint": {
            "branchPrefix": "kaizen/lru-shard-1-",
            "labels": ["kaizen", "performance"],
            "reviewers": ["human"]
        }
    }

    ndjson = json.dumps(proposal)
    md = kaizen_proposal_to_pr_draft(ndjson)

    assert "## Kaizen Proposal: shard-1 sweep p95 = 8.2s" in md
    assert "**Rule ID:** `sweep-latency-p95`" in md
    assert "**Severity:** WARN" in md
    assert "Over the last 24 ticks issachar's tick durationMs has averaged 8,150 ms." in md
    assert "Increase LRU_MAX from 4096 to 16384 on shard-1." in md
    assert "- `50-infra/k8s/unispsc-organism-fleet/shard-1/daemonset.yaml`" in md
    assert 'env UNISPSC_ORGANISM_LRU_MAX: "4096" -> "16384"' in md
    assert "1. Re-apply manifest, wait 30 min" in md
    assert "**Labels:** kaizen, performance" in md
    assert "*This PR was generated by the ecosystem Kaizen PR agent.*" in md

def test_kaizen_proposal_minimal():
    proposal = {
        "kind": "kaizen-proposal"
    }

    ndjson = json.dumps(proposal)
    md = kaizen_proposal_to_pr_draft(ndjson)

    assert "## Kaizen Proposal: No summary provided" in md
    assert "**Rule ID:** `unknown`" in md
    assert "**Severity:** INFO" in md
    assert "### Detail\nNo details provided" in md
    assert "### Suggested Action\nNo description provided" in md
    # Should not contain sections that were omitted
    assert "**Target Files:**" not in md
    assert "**Patch Hint:**" not in md
    assert "### Test Plan" not in md

def test_kaizen_proposal_invalid_json():
    with pytest.raises(ValueError, match="Invalid NDJSON string"):
        kaizen_proposal_to_pr_draft("{invalid json")

def test_kaizen_proposal_invalid_kind():
    proposal = {
        "kind": "other-kind"
    }
    with pytest.raises(ValueError, match="Expected kind 'kaizen-proposal', got 'other-kind'"):
        kaizen_proposal_to_pr_draft(json.dumps(proposal))
